/* This file is autogenerated, do not edit*/
#include "moc_DialogEditFPU.cpp"
#include "moc_DialogEditGPR.cpp"
#include "moc_DialogEditSIMDRegister.cpp"
#include "moc_Float80Edit.cpp"
#include "moc_Plugin.cpp"
#include "moc_RegisterView.cpp"
