SUBDIRS = agguro_be getpostparams geturlparams webvars

debug:
	(cd agguro_be; make debug)
	(cd getpostparams; make debug)
	(cd geturlparams; make debug)
	(cd webvars; make debug)

release:
	(cd agguro_be; make release)
	(cd getpostparams; make release)
	(cd geturlparams; make release)
	(cd webvars; make release)

clean:
	(cd agguro_be; make clean)
	(cd getpostparams; make clean)
	(cd geturlparams; make clean)
	(cd webvars; make clean)